[package]
name = "site"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
tera = "1.0.0-alpha.3"
glob = "0.2"
rayon = "1"
serde = "1"
serde_derive = "1"
sass-rs = "0.2"
html-minifier = "1.1"

errors = { path = "../errors" }
config = { path = "../config" }
utils = { path = "../utils" }
templates = { path = "../templates" }
front_matter = { path = "../front_matter" }
search = { path = "../search" }
imageproc = { path = "../imageproc" }
library = { path = "../library" }

[dev-dependencies]
tempfile = "3"
